"""Self-contained local management console (no CDN or build step required)."""

CONSOLE_HTML = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>WhatsApp Ghost · Local Developer Console</title>
  <style>
    :root{--ink:#111b21;--muted:#667781;--line:#e3e8ea;--canvas:#f5f7f8;--panel:#fff;--green:#00a884;--green2:#008069;--mint:#d9fdd3;--nav:#0b141a;--nav2:#202c33;--danger:#e5484d;--shadow:0 12px 35px #0b141a12}
    *{box-sizing:border-box}body{margin:0;font:14px/1.45 Inter,Segoe UI,system-ui,sans-serif;color:var(--ink);background:var(--canvas)}button,input,select,textarea{font:inherit}button{cursor:pointer}.shell{display:grid;grid-template-columns:250px 1fr;min-height:100vh}
    aside{position:sticky;top:0;height:100vh;background:var(--nav);color:#e9edef;padding:22px 14px;display:flex;flex-direction:column}.brand{display:flex;gap:11px;align-items:center;padding:0 10px 24px}.mark{width:38px;height:38px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(145deg,#25d366,var(--green2));font-size:21px;box-shadow:0 8px 24px #00a88444}.brand b{display:block;font-size:17px}.brand small{color:#8696a0}
    nav button{width:100%;border:0;border-radius:10px;padding:11px 12px;margin:2px 0;text-align:left;background:transparent;color:#aebac1;display:flex;gap:11px;align-items:center}nav button:hover,nav button.active{background:var(--nav2);color:#fff}nav .icon{width:20px;text-align:center}.aside-foot{margin-top:auto;padding:13px;border:1px solid #2a3942;border-radius:12px;color:#8696a0;font-size:12px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#25d366;margin-right:6px;box-shadow:0 0 0 4px #25d36622}
    main{min-width:0}.topbar{height:68px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 30px;position:sticky;top:0;z-index:5}.crumb{color:var(--muted)}.crumb strong{color:var(--ink)}.mode{padding:7px 11px;border-radius:999px;background:#e8f8f3;color:var(--green2);font-weight:700;font-size:12px}.content{padding:28px 30px;max-width:1450px;margin:auto}.page{display:none}.page.active{display:block}.title-row{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:22px}.title-row h1{margin:0 0 3px;font-size:26px;letter-spacing:-.6px}.title-row p{margin:0;color:var(--muted)}
    .grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px}.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;box-shadow:var(--shadow);padding:20px}.span3{grid-column:span 3}.span4{grid-column:span 4}.span5{grid-column:span 5}.span6{grid-column:span 6}.span7{grid-column:span 7}.span8{grid-column:span 8}.span12{grid-column:span 12}.metric small{color:var(--muted);font-weight:600}.metric strong{display:block;font-size:29px;margin-top:8px}.metric .accent{color:var(--green2)}h2{font-size:16px;margin:0 0 15px}.subtle{color:var(--muted)}
    .btn{border:0;border-radius:9px;padding:9px 14px;font-weight:700;background:var(--green2);color:#fff}.btn:hover{filter:brightness(.94)}.btn.secondary{background:#eef2f3;color:var(--ink)}.btn.danger{background:#fff0f0;color:var(--danger)}.btn.small{padding:6px 10px;font-size:12px}.actions{display:flex;gap:8px;flex-wrap:wrap}
    label{display:block;font-size:12px;font-weight:700;color:#54656f;margin:11px 0 5px}.field{width:100%;border:1px solid #cbd5d9;border-radius:9px;padding:10px 11px;background:#fff;outline:none}.field:focus{border-color:var(--green);box-shadow:0 0 0 3px #00a8841c}textarea.field{min-height:90px;resize:vertical}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-backdrop{display:none;position:fixed;inset:0;background:#0b141a99;z-index:20;place-items:center}.modal-backdrop.open{display:grid}.modal{background:#fff;width:min(520px,calc(100vw - 32px));max-height:90vh;overflow:auto;border-radius:16px;padding:23px;box-shadow:0 24px 80px #0005}.modal-head{display:flex;justify-content:space-between;align-items:center}.x{border:0;background:none;font-size:22px;color:var(--muted)}
    .list{display:grid;gap:10px}.row{display:flex;align-items:center;gap:12px;border:1px solid var(--line);border-radius:11px;padding:13px}.avatar{flex:0 0 38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#dff5ee;color:var(--green2);font-weight:800}.row-main{min-width:0;flex:1}.row-main b,.row-main small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.row-main small{color:var(--muted)}.tag{font-size:11px;font-weight:800;padding:4px 8px;border-radius:999px;background:#e8f8f3;color:var(--green2)}.tag.gray{background:#eef2f3;color:#54656f}.tag.amber{background:#fff4d6;color:#8b6508}
    code,.code{font:12px ui-monospace,SFMono-Regular,Consolas,monospace}.secret{display:flex;gap:8px;align-items:center;background:#f4f6f7;border-radius:8px;padding:8px 10px;min-width:0}.secret code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}.endpoint{background:#111b21;color:#d6e1e5;border-radius:12px;padding:16px;overflow:auto}.endpoint .green{color:#53bdeb}.empty{text-align:center;padding:34px;color:var(--muted)}
    .phone-wrap{height:690px;display:grid;grid-template-columns:300px 1fr;background:#efeae2;border-radius:15px;overflow:hidden;border:1px solid var(--line);box-shadow:var(--shadow)}.chat-side{background:#fff;border-right:1px solid var(--line)}.phone-head{height:62px;background:#f0f2f5;padding:10px 14px;display:flex;align-items:center;gap:10px}.phone-head small,.chat-title small{display:block}.search{margin:8px 10px;width:calc(100% - 20px);border:0;border-radius:9px;padding:9px 12px;background:#f0f2f5}.conversation{padding:12px 14px;display:flex;gap:11px;background:#f0f2f5;border-top:1px solid #fff}.chat-main{display:grid;grid-template-rows:62px 1fr 62px;background-color:#efeae2;background-image:radial-gradient(#0b141a09 1px,transparent 1px);background-size:18px 18px}.chat-title{background:#f0f2f5;display:flex;align-items:center;padding:9px 16px;gap:10px}.messages{padding:22px clamp(18px,7vw,80px);overflow:auto;display:flex;flex-direction:column;gap:7px}.bubble{max-width:72%;padding:7px 9px 5px;border-radius:8px;background:#fff;box-shadow:0 1px 1px #0002;align-self:flex-start;white-space:pre-wrap}.bubble.mine{background:var(--mint);align-self:flex-end}.bubble small{float:right;color:#667781;font-size:10px;margin:5px 0 0 11px}.composer{background:#f0f2f5;padding:10px 13px;display:flex;gap:9px}.composer input{flex:1;border:0;border-radius:9px;padding:10px 13px}.raw{font:11px ui-monospace,monospace;color:#54656f;margin-top:5px;display:none}.bubble.show-raw .raw{display:block}
    .toast{position:fixed;right:20px;bottom:20px;z-index:50;background:#111b21;color:#fff;padding:12px 15px;border-radius:10px;box-shadow:0 12px 40px #0004;transform:translateY(100px);opacity:0;transition:.25s}.toast.show{transform:none;opacity:1}.status-line{display:flex;gap:8px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line)}
    @media(max-width:950px){.shell{grid-template-columns:76px 1fr}.brand div:last-child,nav button span:last-child,.aside-foot{display:none}.brand{padding:0 4px 20px}.brand .mark{margin:auto}nav button{justify-content:center}.span3,.span4,.span5,.span6,.span7,.span8{grid-column:span 12}.phone-wrap{grid-template-columns:1fr}.chat-side{display:none}.content{padding:20px}.topbar{padding:0 20px}}@media(max-width:550px){.shell{display:block}aside{height:58px;position:fixed;z-index:10;bottom:0;top:auto;width:100%;padding:5px;display:block}.brand,.aside-foot{display:none}nav{display:flex;justify-content:space-around}nav button{width:auto;margin:0;padding:9px 12px}main{padding-bottom:58px}.topbar{height:58px}.content{padding:16px}.phone-wrap{height:72vh}.form-row{grid-template-columns:1fr}.title-row{align-items:flex-start;gap:12px}.title-row h1{font-size:22px}}
  </style>
</head>
<body><div class="shell">
  <aside><div class="brand"><div class="mark">👻</div><div><b>WhatsApp Ghost</b><small>Local developer cloud</small></div></div>
    <nav>
      <button class="active" data-page="overview"><span class="icon">⌂</span><span>Overview</span></button>
      <button data-page="apps"><span class="icon">⌘</span><span>API Apps</span></button>
      <button data-page="resources"><span class="icon">◫</span><span>WABA Resources</span></button>
      <button data-page="templates"><span class="icon">▤</span><span>Templates</span></button>
      <button data-page="webhooks"><span class="icon">↯</span><span>Webhooks</span></button>
      <button data-page="simulator"><span class="icon">◉</span><span>Phone Simulator</span></button>
    </nav><div class="aside-foot"><span class="dot"></span>Runs only on your machine<br><span id="base-small">127.0.0.1:8787</span></div>
  </aside>
  <main><header class="topbar"><div class="crumb">Ghost Console / <strong id="crumb">Overview</strong></div><div class="mode" id="mode">STRICT MODE</div></header>
  <div class="content">
    <section class="page active" id="overview"><div class="title-row"><div><h1>Your local WhatsApp platform</h1><p>Create, configure, test, and inspect without publishing anything.</p></div><button class="btn" onclick="showModal('app-modal')">＋ Create app</button></div>
      <div class="grid"><div class="card metric span3"><small>Developer apps</small><strong id="m-apps">—</strong></div><div class="card metric span3"><small>Business numbers</small><strong id="m-numbers">—</strong></div><div class="card metric span3"><small>Simulated customers</small><strong id="m-users">—</strong></div><div class="card metric span3"><small>Messages</small><strong class="accent" id="m-messages">—</strong></div>
      <div class="card span7"><h2>Drop-in API endpoint</h2><p class="subtle">Keep your Cloud API path and payload. Replace the hostname and use a local token.</p><div class="endpoint"><span class="green">POST</span> <span id="endpoint">http://127.0.0.1:8787/v25.0/PHONE_LOCAL/messages</span></div><div class="actions" style="margin-top:14px"><button class="btn secondary" onclick="copyText(config.base_url)">Copy base URL</button><button class="btn secondary" onclick="location.href='/docs'">Open API docs ↗</button></div></div>
      <div class="card span5"><h2>Quick start</h2><div class="status-line"><span class="tag">1</span><div><b>Open a customer chat</b><div class="subtle">Send an inbound message to open the 24-hour window.</div></div></div><div class="status-line"><span class="tag">2</span><div><b>Call the Cloud API path</b><div class="subtle">Use the local Bearer token from API Apps.</div></div></div><div class="status-line"><span class="tag">3</span><div><b>Inspect webhooks</b><div class="subtle">See raw signed deliveries and replay failures.</div></div></div></div></div>
    </section>
    <section class="page" id="apps"><div class="title-row"><div><h1>API Apps</h1><p>Local equivalents of developer apps, secrets, and access tokens.</p></div><button class="btn" onclick="showModal('app-modal')">＋ Create app</button></div><div class="list" id="app-list"></div></section>
    <section class="page" id="resources"><div class="title-row"><div><h1>WABA Resources</h1><p>Manage business accounts and registered sender numbers.</p></div><button class="btn" onclick="showModal('business-modal')">＋ Add business</button></div><div class="list" id="business-list"></div></section>
    <section class="page" id="templates"><div class="title-row"><div><h1>Message Templates</h1><p>Create approved local templates with positional variables such as {{1}}.</p></div><button class="btn" onclick="showModal('template-modal')">＋ New template</button></div><div class="list" id="template-list"></div></section>
    <section class="page" id="webhooks"><div class="title-row"><div><h1>Webhook Inspector</h1><p>Raw HMAC-signed events, delivery attempts, responses, and replay.</p></div><button class="btn" onclick="showModal('webhook-modal')">＋ Subscribe URL</button></div><div class="list" id="webhook-list"></div></section>
    <section class="page" id="simulator"><div class="title-row"><div><h1>Phone Simulator</h1><p>A browser companion to the Textual multi-terminal clients. Click a message to inspect its payload.</p></div><div class="actions"><select class="field" id="phone-select" onchange="switchPhone(this.value)" style="width:auto"></select><button class="btn secondary" onclick="openPhoneTab()">↗ Open phone tab</button><button class="btn secondary" onclick="showModal('phone-modal')">＋ Customer</button><button class="btn secondary" onclick="advanceClock()">Advance 25h</button></div></div>
      <div class="phone-wrap"><div class="chat-side"><div class="phone-head"><div class="avatar">YG</div><div><b>Your Ghost Phone</b><small class="subtle" id="current-wa">15550002001</small></div></div><input class="search" placeholder="Search or start new chat"><div class="conversation"><div class="avatar">GD</div><div class="row-main"><b>Ghost Demo Business</b><small>Local business account</small></div></div></div>
      <div class="chat-main"><div class="chat-title"><div class="avatar">GD</div><div><b>Ghost Demo Business</b><small class="subtle">local sandbox • always inspectable</small></div></div><div class="messages" id="chat-messages"></div><form class="composer" id="chat-form"><input id="chat-input" autocomplete="off" placeholder="Message as customer"><button class="btn" type="submit">Send</button></form></div></div>
    </section>
  </div></main>
</div>

<div class="modal-backdrop" id="app-modal"><form class="modal" onsubmit="createApp(event)"><div class="modal-head"><h2>Create a local API app</h2><button type="button" class="x" onclick="hideModal('app-modal')">×</button></div><p class="subtle">A local app gets an ID, app secret, and Bearer token instantly.</p><label>App name</label><input class="field" id="app-name" required placeholder="Order notifications"><div class="actions" style="margin-top:18px"><button class="btn">Create app</button><button type="button" class="btn secondary" onclick="hideModal('app-modal')">Cancel</button></div></form></div>
<div class="modal-backdrop" id="business-modal"><form class="modal" onsubmit="createBusiness(event)"><div class="modal-head"><h2>Add a business and sender</h2><button type="button" class="x" onclick="hideModal('business-modal')">×</button></div><div class="form-row"><div><label>Business name</label><input class="field" id="biz-name" required placeholder="Acme Support"></div><div><label>Verified display name</label><input class="field" id="biz-verified" placeholder="Acme"></div></div><label>Business phone number</label><input class="field" id="biz-phone" required placeholder="15550003000"><div class="actions" style="margin-top:18px"><button class="btn">Create resources</button><button type="button" class="btn secondary" onclick="hideModal('business-modal')">Cancel</button></div></form></div>
<div class="modal-backdrop" id="template-modal"><form class="modal" onsubmit="createTemplate(event)"><div class="modal-head"><h2>Create template</h2><button type="button" class="x" onclick="hideModal('template-modal')">×</button></div><div class="form-row"><div><label>WABA</label><select class="field" id="tpl-waba"></select></div><div><label>Category</label><select class="field" id="tpl-category"><option>UTILITY</option><option>MARKETING</option><option>AUTHENTICATION</option></select></div></div><div class="form-row"><div><label>Name</label><input class="field" id="tpl-name" required placeholder="order_update"></div><div><label>Language</label><input class="field" id="tpl-language" value="en_US" required></div></div><label>Body</label><textarea class="field" id="tpl-body" required placeholder="Hello {{1}}, order {{2}} is ready."></textarea><div class="actions" style="margin-top:18px"><button class="btn">Create and approve</button><button type="button" class="btn secondary" onclick="hideModal('template-modal')">Cancel</button></div></form></div>
<div class="modal-backdrop" id="webhook-modal"><form class="modal" onsubmit="createWebhook(event)"><div class="modal-head"><h2>Subscribe a webhook</h2><button type="button" class="x" onclick="hideModal('webhook-modal')">×</button></div><label>WABA</label><select class="field" id="wh-waba"></select><label>Callback URL</label><input class="field" id="wh-url" type="url" required placeholder="http://127.0.0.1:9000/webhook"><label>Verify token (optional)</label><input class="field" id="wh-verify" placeholder="my-project-verify-token"><p class="subtle">When supplied, Ghost calls your URL with the real hub.challenge flow before saving it. Events are signed using the local app secret.</p><div class="actions"><button class="btn">Verify and subscribe</button><button type="button" class="btn secondary" onclick="hideModal('webhook-modal')">Cancel</button></div></form></div>
<div class="modal-backdrop" id="phone-modal"><form class="modal" onsubmit="createPhone(event)"><div class="modal-head"><h2>Create simulated customer</h2><button type="button" class="x" onclick="hideModal('phone-modal')">×</button></div><label>Phone number</label><input class="field" id="user-phone" required placeholder="15550002002"><label>Display name</label><input class="field" id="user-name" required placeholder="Alice"><div class="actions" style="margin-top:18px"><button class="btn">Create phone</button><button type="button" class="btn secondary" onclick="hideModal('phone-modal')">Cancel</button></div></form></div>
<div class="toast" id="toast"></div>
<script>
const requestedPhone=new URLSearchParams(location.search).get('phone');
let config={}, businesses=[], users=[], currentWa=requestedPhone||'15550002001', phoneSocket=null, reconnectTimer=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function req(url,options={}){const r=await fetch(url,options);let data;try{data=await r.json()}catch{data={error:await r.text()}}if(!r.ok)throw new Error(data?.error?.error_data?.details||data?.error||data?.detail||r.statusText);return data}
function toast(msg,bad=false){const e=$('#toast');e.textContent=msg;e.style.background=bad?'#b4232a':'#111b21';e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function showModal(id){$('#'+id).classList.add('open')}function hideModal(id){$('#'+id).classList.remove('open')}function copyText(v){navigator.clipboard.writeText(v);toast('Copied to clipboard')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active');$('#crumb').textContent=b.textContent.trim();if(b.dataset.page==='simulator')loadChat();if(b.dataset.page==='webhooks')loadWebhooks()});
async function loadAll(){try{config=await req('/_sandbox/config');const [apps,biz,userResult,msgs]=await Promise.all([req('/_sandbox/apps'),req('/_sandbox/businesses'),req('/_sandbox/phones'),req('/_sandbox/messages?limit=500')]);businesses=biz.data;users=userResult.data;if(!users.some(u=>u.wa_id===currentWa)&&users.length)currentWa=users[0].wa_id;$('#mode').textContent=config.mode.toUpperCase()+' MODE';$('#base-small').textContent=config.base_url.replace(/^https?:\/\//,'');$('#endpoint').textContent=config.base_url+'/v25.0/PHONE_LOCAL/messages';$('#m-apps').textContent=apps.data.length;$('#m-numbers').textContent=businesses.reduce((n,b)=>n+b.phone_numbers.length,0);$('#m-users').textContent=users.length;$('#m-messages').textContent=msgs.data.length;renderApps(apps.data);renderBusinesses();fillWabas();fillPhones();await loadTemplates();await loadWebhooks();await loadChat()}catch(e){toast(e.message,true)}}
function renderApps(items){$('#app-list').innerHTML=items.map(a=>`<div class="card row"><div class="avatar">⌘</div><div class="row-main"><b>${esc(a.name)} <span class="tag">ACTIVE</span></b><small>${esc(a.id)} · created ${new Date(a.created_at).toLocaleString()}</small><label>Access token</label><div class="secret"><code>${esc(a.access_token)}</code><button class="btn small secondary" onclick="copyText('${esc(a.access_token)}')">Copy</button></div><label>App secret</label><div class="secret"><code>${esc(a.app_secret)}</code><button class="btn small secondary" onclick="copyText('${esc(a.app_secret)}')">Copy</button></div></div><button class="btn small secondary" onclick="rotateToken('${esc(a.id)}')">Rotate token</button></div>`).join('')||'<div class="card empty">No apps yet.</div>'}
function renderBusinesses(){const list=$('#business-list');list.innerHTML=businesses.map(b=>`<div class="card"><div class="row" style="border:0;padding:0"><div class="avatar">B</div><div class="row-main"><b>${esc(b.name)}</b><small>Business ${esc(b.business_id)} · WABA ${esc(b.id)}</small></div><span class="tag">LOCAL</span></div><div class="list" style="margin-top:14px">${b.phone_numbers.map(p=>`<div class="row"><div class="avatar">☎</div><div class="row-main"><b>${esc(p.verified_name)}</b><small>+${esc(p.display_phone_number)} · ID ${esc(p.id)}</small></div><span class="tag">${esc(p.quality_rating)}</span><span class="tag gray">${esc(p.registration_status)}</span></div>`).join('')}</div></div>`).join('')}
function fillWabas(){const opts=businesses.map(b=>`<option value="${esc(b.id)}">${esc(b.name)} · ${esc(b.id)}</option>`).join('');$('#tpl-waba').innerHTML=opts;$('#wh-waba').innerHTML=opts}
function fillPhones(){$('#phone-select').innerHTML=users.map(u=>`<option value="${esc(u.wa_id)}" ${u.wa_id===currentWa?'selected':''}>${esc(u.display_name)} · +${esc(u.wa_id)}</option>`).join('');$('#current-wa').textContent=currentWa}
function switchPhone(wa){currentWa=wa;$('#current-wa').textContent=wa;history.replaceState(null,'','/console?phone='+encodeURIComponent(wa)+'#simulator');connectPhoneSocket();loadChat()}
function openPhoneTab(){window.open('/console?phone='+encodeURIComponent(currentWa)+'#simulator','ghost-phone-'+currentWa)}
function connectPhoneSocket(){if(phoneSocket){phoneSocket.onclose=null;phoneSocket.close()}if(reconnectTimer)clearTimeout(reconnectTimer);const scheme=location.protocol==='https:'?'wss':'ws';const socketWa=currentWa;phoneSocket=new WebSocket(`${scheme}://${location.host}/_sandbox/clients/${encodeURIComponent(socketWa)}`);phoneSocket.onmessage=()=>{if(currentWa===socketWa)loadChat()};phoneSocket.onclose=()=>{if(currentWa===socketWa)reconnectTimer=setTimeout(connectPhoneSocket,1500)}}
async function loadTemplates(){if(!config.access_token)return;let all=[];for(const b of businesses){try{const d=await req(`/v25.0/${b.id}/message_templates`,{headers:{Authorization:'Bearer '+config.access_token}});all.push(...d.data)}catch{}}$('#template-list').innerHTML=all.map(t=>`<div class="card row"><div class="avatar">T</div><div class="row-main"><b>${esc(t.name)} <span class="tag">${esc(t.status)}</span></b><small>${esc(t.language)} · ${esc(t.category)} · ${esc(t.id)}</small><div style="margin-top:7px">${esc(t.components?.find(c=>c.type==='BODY')?.text||'')}</div></div></div>`).join('')||'<div class="card empty">No templates.</div>'}
async function loadWebhooks(){const d=await req('/_sandbox/webhooks');$('#webhook-list').innerHTML=d.data.map(w=>`<div class="card row"><div class="avatar">↯</div><div class="row-main"><b>${esc(w.event_type)} <span class="tag ${w.status==='delivered'?'':'amber'}">${esc(w.status)}</span></b><small>${esc(w.destination_url||'No subscription configured')} · ${esc(w.id)}</small><details><summary class="subtle" style="cursor:pointer;margin-top:7px">Raw payload and signature</summary><div class="endpoint code" style="margin-top:7px">${esc(JSON.stringify(w.request_body,null,2))}</div><div class="secret"><code>${esc(w.signature)}</code></div></details></div>${w.destination_url?`<button class="btn small secondary" onclick="replay('${esc(w.id)}')">Replay</button>`:''}</div>`).join('')||'<div class="card empty">Events appear here as messages and statuses are created.</div>'}
async function loadChat(){const d=await req('/_sandbox/messages?wa_id='+currentWa+'&limit=200');const items=d.data.reverse();$('#chat-messages').innerHTML=items.map(m=>{const p=m.payload,body=m.message_type==='text'?(typeof p.text==='string'?p.text:(p.text?.body||'')):m.message_type==='template'?'Template: '+(p.template?.name||''):('['+m.message_type+']');return `<div class="bubble ${m.direction==='inbound'?'mine':''}" onclick="this.classList.toggle('show-raw')">${esc(body)}<small>${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · ${esc(m.status)}</small><div class="raw">${esc(JSON.stringify(p,null,2))}</div></div>`}).join('')||'<div class="empty">Send a message below to open the 24-hour service window.</div>';const box=$('#chat-messages');box.scrollTop=box.scrollHeight}
async function createApp(e){e.preventDefault();try{await req('/_sandbox/apps',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#app-name').value})});hideModal('app-modal');e.target.reset();toast('App and credentials created');loadAll()}catch(x){toast(x.message,true)}}
async function rotateToken(id){try{const d=await req(`/_sandbox/apps/${id}/rotate-token`,{method:'POST'});copyText(d.access_token);toast('Token rotated and copied');loadAll()}catch(e){toast(e.message,true)}}
async function createBusiness(e){e.preventDefault();try{await req('/_sandbox/businesses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#biz-name').value,verified_name:$('#biz-verified').value,display_phone_number:$('#biz-phone').value})});hideModal('business-modal');e.target.reset();toast('Business, WABA, and sender created');loadAll()}catch(x){toast(x.message,true)}}
async function createTemplate(e){e.preventDefault();try{const w=$('#tpl-waba').value;await req(`/v25.0/${w}/message_templates`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+config.access_token},body:JSON.stringify({name:$('#tpl-name').value,language:$('#tpl-language').value,category:$('#tpl-category').value,components:[{type:'BODY',text:$('#tpl-body').value}]})});hideModal('template-modal');e.target.reset();toast('Template approved locally');loadTemplates()}catch(x){toast(x.message,true)}}
async function createWebhook(e){e.preventDefault();try{await req(`/v25.0/${$('#wh-waba').value}/subscribed_apps`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+config.access_token},body:JSON.stringify({callback_url:$('#wh-url').value,verify_token:$('#wh-verify').value||undefined})});hideModal('webhook-modal');e.target.reset();toast('Webhook verified and subscribed')}catch(x){toast(x.message,true)}}
async function createPhone(e){e.preventDefault();try{const d=await req('/_sandbox/phones',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wa_id:$('#user-phone').value,display_name:$('#user-name').value})});currentWa=d.wa_id;$('#current-wa').textContent=currentWa;hideModal('phone-modal');e.target.reset();toast('Simulated phone created');loadAll()}catch(x){toast(x.message,true)}}
async function replay(id){try{await req(`/_sandbox/webhooks/${id}/replay`,{method:'POST'});toast('Delivery replayed');loadWebhooks()}catch(e){toast(e.message,true)}}
async function advanceClock(){try{const d=await req('/_sandbox/clock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'advance',value:'25h'})});toast('Clock is now '+d.now)}catch(e){toast(e.message,true)}}
$('#chat-form').onsubmit=async e=>{e.preventDefault();const input=$('#chat-input'),text=input.value.trim();if(!text)return;input.value='';try{await req(`/_sandbox/phones/${currentWa}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'text',text})});await loadChat();await loadWebhooks()}catch(x){toast(x.message,true)}};
document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));if(location.hash==='#simulator'||requestedPhone){document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));document.querySelector('nav button[data-page="simulator"]').classList.add('active');$('#simulator').classList.add('active');$('#crumb').textContent='Phone Simulator'}loadAll().then(connectPhoneSocket);
</script></body></html>'''
